name: EPG Updater

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Script
        id: epg_script  # ID used to reference outputs
        run: python main.py

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # This line pulls the 'total' variable from the epg_script step
          commit_message: "EPG Update: ${{ steps.epg_script.outputs.total }} channels"
          file_pattern: 'merged_epg.xml merged_epg.xml.gz epg_cache.json'

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Indian EPG Update"
          body: "Total Channels: ${{ steps.epg_script.outputs.total }}\nDate: "
          files: merged_epg.xml.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
